### ISSUE TITLE
read ref-delta cause infinite loop...

### ISSUE THREAD

**Issue by li-yinan** [creationix/js-git#128]
read ref-delta cause infinite loop...
https://github.com/creationix/js-git/blob/master/mixins/fs-db.js#L225
```javascript
if (entry.type === "ref-delta") {
    return loadRaw.call(repo, hash, onBase);
}
```

```javascript
if (entry.type === "ref-delta") {
    return loadRaw.call(repo, entry.ref, onBase);
}
```

**Comment by creationix** [comment]
Thanks.  I guess I've never ran across a case that exercises this code.  How did you run across it?

**Comment by li-yinan** [comment]
I plan to make a update program for my nw.js client, the core tech of git make the update small and zipped, it also can calculate the diff of two version, so the client can update from any version.

I found js-git is pretty good, so I add some high-level api, such as fetch, checkout, just some wrapper for js-git, I push the compiled code to github, the client fetch from github every 10 minute, and checkout code from .git folder when the client reboot.

It works well for a long time, but one day it run into infinite loop, maybe I push a file similar to an old one, and github calculate the difference, change the old one into a ref-delta.

Btw, high-level api from official repository is very much appreciated.
