### ISSUE TITLE
pack-ops mixing doesn't work

### ISSUE THREAD

**Issue by TheKnarf** [creationix/js-git#134]
name | version
--- | ---
MacOS Sierra | v10.12.5
Node | v8.1.3
Npm | 5.3.0

My `package.json` lists `"js-git": "^0.7.8"` as a dependency.

I define my repo like this:

```
var modes = require('js-git/lib/modes');

// Create a repo by creating a plain object.
var repo = {};

require('js-git/mixins/mem-db')(repo);
require('js-git/mixins/create-tree')(repo);
require('js-git/mixins/pack-ops')(repo);
require('js-git/mixins/walkers')(repo);
require('js-git/mixins/read-combiner')(repo);
require('js-git/mixins/formats')(repo);
```

Then I create some blobs, a tree, and a commit. Now what I want to do is make a pack from this.

First I tried the following (as stated in the [documentation](https://github.com/creationix/js-git/blob/master/doc/mixins/pack-ops.md)):

```
repo.pack(commitHash, {}, (err, stream) => {
	if (err) throw err;

	stream.read(onRead);
	function onRead(err, item) {
		if (err) throw err;
		console.log(item);
		if (item) stream.read(onRead);
	}
});
```

However, that complains that `read` isn't defined/a function. Doing a `console.log(stream)` shows me that it only contains a function called `take`. So my new code looks like this:

```
repo.pack(commitHash, {}, (err, stream) => {
	if (err) throw err;

	console.log(stream);
	stream.take((err, buffer) => {
		console.log(buffer);
	});
});
```

This, however, complains that `onError` is not defined.

```
{ take: [Function: take] }
<Buffer 50 41 43 4b 00 00 00 02 00 00 00 28>
node_modules/js-git/mixins/pack-ops.js:187
    if (err) return onError(err);
                    ^

TypeError: onError is not a function
    at onData (node_modules/js-git/mixins/pack-ops.js:187:21)
    at node_modules/js-git/mixins/pack-ops.js:158:27
    at node_modules/js-git/mixins/mem-db.js:93:5
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
```

Seems that the pack-ops code is referencing a onError function that does not exist.

**Comment by TheKnarf** [comment]
[`applyParser`](https://github.com/creationix/js-git/blob/master/mixins/pack-ops.js#L181) seem to need a `onError` argument, but is called without one here:

[`return callback(null, applyParser({ take: take }, encodePack));`](https://github.com/creationix/js-git/blob/master/mixins/pack-ops.js#L147)

I also don't understand how to use the `stream.take` that I get from calling `repo.pack`;

**Comment by TheKnarf** [comment]
This seems to work:

```
repo.pack(hashes, {}, (err, stream) => {
	if (err) throw err;

	function readStream() {
		stream.take((err, data) => {
			if(err) throw err;
			if(data === undefined) return;
			process.stdout.write(data);
			readStream();
		});
	}
	readStream();
});
```

Perhaps the documentation should be updated.

**Comment by creationix** [comment]
Yep you're right.  Thanks for digging in.  I completely forgot about this and wouldn't have been able to help.

https://github.com/creationix/js-git/blob/master/mixins/pack-ops.js#L16-L18

**Comment by creationix** [comment]
I am confused

**Comment by creationix** [comment]
If you could check the modified version in the README, let me know if it works.
