### ISSUE TITLE
Replace github-db with private git server?

### ISSUE THREAD

**Issue by bobby-brennan** [creationix/js-git#138]
First off - thanks for maintaining this. It enables a lot of awesome browser-based workflows. I just made a small donation via bountysource, as it's been a huge help in my projects.

Currently I'm using `github-db` from [js-github](https://github.com/creationix/js-github) to work with code, but I'm trying to create the option of using a private Git server (where CORS is enabled). I've been looking at [this clone example](https://github.com/creationix/clone-test/blob/master/src/main.js), but that seems to clone the entire repo rather than working analogously to `github-db`.

Is there a drop-in replacement for `github-db` that uses a custom Git server? Is that even possible?

Thanks again, any help appreciated.

-Bobby

**Comment by TheKnarf** [comment]
`js-github` uses the Github Rest API, not the standard git protocol.

What do you mean by custom Git server?
Are you trying to setup a GitLab, Bitbucket or Gogs server?

Depending on what you're trying to setup and if that server has a custom HTTP API it should be possible to make some sort of adapter. However, as far as I know, there's no ready-made adapter out there yet for other platforms.

**Comment by bobby-brennan** [comment]
I'm using [this project](https://github.com/cirocosta/gitserver-http) as a git backend.

My solution was to use `fs-db`. I created HTTP implementations of `readFile`, `writeFile`, `readChunk`, `readDir`, and `rename` on the git server, and then told `fs-db` to hit those HTTP endpoints rather than reading from local files.

It took some messing around with encodings etc but it seems to be stable now.

**Comment by bobby-brennan** [comment]
The project is up at [datafire.io](https://app.datafire.io). There's a [major open source component](https://github.com/DataFire/DataFire), but the frontend (where we use js-git) is proprietary
