### ISSUE TITLE
In-memory file system

### ISSUE THREAD

**Issue by streamich** [creationix/js-git#139]
Is it possible to use `js-git` with [`memfs`](https://github.com/streamich/memfs)? If not, where would be a good point for me add it?

**Comment by TheKnarf** [comment]
`js-git` has it's own internal implementation of an in-memory filesystem. You can see the sparsely documentation of it [here](https://github.com/creationix/js-git/blob/master/doc/mixins/mem-db.md). It should be possible to add memfs support, but last time I used it the internal implementation was working just fine.

**Comment by TheKnarf** [comment]
This should also work:

```
import { fs } from 'memfs';
require('js-git/mixins/fs-db')(repo, fs);
```
